# Schema for the configuration files of the date time day module.

# Date time day field type.
field.storage_settings.datetimeday:
  type: mapping
  label: 'Date time day storage settings'
  mapping:
    datetime_type:
      type: string
      label: 'Date type'
    time_type:
      type: string
      label: 'Time type'

field.field_settings.datetimeday:
  type: field.field_settings.datetime
  label: 'Date time day field settings'

field.value.datetimeday:
  type: mapping
  label: 'Default value'
  mapping:
    default_date_type:
      type: string
      label: 'Default date type'
    default_date:
      type: string
      label: 'Default date value'
    default_start_time_type:
      type: string
      label: 'Default start time type'
    default_start_time:
      type: string
      label: 'Default start time value'
    default_end_time_type:
      type: string
      label: 'Default end time type'
    default_end_time:
      type: string
      label: 'Default end time value'

field.formatter.settings.datetimeday_base:
  type: mapping
  mapping:
    timezone_override:
      type: string
      label: 'Time zone override'

field.formatter.settings.datetimeday_default:
  type: field.formatter.settings.datetimeday_base
  label: 'Date time day default display format settings'
  mapping:
    day_separator:
      type: label
      label: 'Date separator'
      translation context: 'Date separator'
    time_separator:
      type: label
      label: 'Time separator'
      translation context: 'Time separator'
    format_type:
      type: string
      label: 'Day format'
    time_format_type:
      type: string
      label: 'Time format'

field.formatter.settings.datetimeday_h_i_partial_time:
  type: field.formatter.settings.datetimeday_base
  label: 'Date time day plain display format settings'
  mapping:
    day_separator:
      type: label
      label: 'Date separator'
      translation context: 'Date separator'
    time_separator:
      type: label
      label: 'Time separator'
      translation context: 'Time separator'
    format_type:
      type: string
      label: 'Date format'
    time_format_type:
      type: string
      label: 'Time format'
